const STATUS_CODE = {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 422,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
    UNPROCESSABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500,
    NETWORK_CONNECT_TIMEOUT_ERROR: 599,
    DISCONNECT_NETWORK_ERROR: 600,
};

export default STATUS_CODE;