export const Colors = {
    primary100: '#ffffff',
    primary500: '#cccccc',
    primary800: '#333333',
    error100: '#fcdcbf',
    error500: '#f37c13',
    blue: '#1d82f5',
    indigo: '#6610f2',
    purple: '#6f42c1',
    pink: '#ea4c89',
    red: '#D30000',
    orange: '#fd7e14',
    yellow: '#FCBD01',
    green: '#28a745',
    teal: '#20c997',
    cyan: '#17a2b8',
    white: '#fff',
    gray: '#6c757d',
    grayDark: '#343a40',
    primary: '#1d82f5',
    secondary: '#6c757d',
    success: '#28a745',
    info: '#17a2b8',
    warning: '#FCBD01',
    danger: '#D30000',
    light: '#f8f9fa',
    dark: '#343a40', 
    darkBlue: '#1d82f5',
    lightGray: '#f8f9fa',
    lightGray2: '#E9E9E9',
    lightBlue: '#e7f5ff',
  }

export const FONT = {
  NORMAL_16_BOLD_WHITE: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.white,
  },
  NORMAL_16_BOLD_BLACK: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.black,
  },
  NORMAL_16_BOLD_PRIMARY: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.primary,
  },
  NORMAL_20_BOLD_WHITE: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.white,
  },
  NORMAL_20_BOLD_BLACK: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.black,
  },
  NORMAL_20_BOLD_PRIMARY: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.primary,
  },
  NORMAL_16_WHITE: {
    fontSize: 16,
    color: Colors.white,
  },
  NORMAL_16_BLACK: {
    fontSize: 16,
    color: Colors.black,
  },
  NORMAL_16_PRIMARY: {
    fontSize: 16,
    color: Colors.primary,
  },
}
